
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KreditrechnerLAP.logic
{

using System;
    using System.Collections.Generic;
    
public partial class Arbeitgeber
{

    public Arbeitgeber()
    {

        this.Kunde = new HashSet<Kunde>();

    }


    public int ID { get; set; }

    public Nullable<int> FKBeschaeftigungsart { get; set; }

    public Nullable<int> FKBranche { get; set; }

    public string Firmenname { get; set; }

    public Nullable<System.DateTime> BeschaeftigtSeit { get; set; }



    public virtual Beschaeftigungsart Beschaeftigungsart { get; set; }

    public virtual Branche Branche { get; set; }

    public virtual ICollection<Kunde> Kunde { get; set; }

}

}
