//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KreditrechnerLAP.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Einstellungen
    {
        public int ID { get; set; }
        public decimal NormalZins { get; set; }
        public decimal EffektiverZins { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
