
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KreditrechnerLAP.logic
{

using System;
    using System.Collections.Generic;
    
public partial class FinanzielleSituation
{

    public int ID { get; set; }

    public Nullable<decimal> NettoEinkommen { get; set; }

    public Nullable<decimal> Wohnkosten { get; set; }

    public Nullable<decimal> EinkünfteAlimente { get; set; }

    public Nullable<decimal> Unterhaltszahlung { get; set; }

    public Nullable<decimal> Ratenverpflichtung { get; set; }



    public virtual Kunde Kunde { get; set; }

}

}
