//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KreditrechnerLAP.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kredit
    {
        public int ID { get; set; }
        public Nullable<decimal> Betrag { get; set; }
        public Nullable<int> Zeitraum { get; set; }
        public Nullable<bool> Bewilligt { get; set; }
    
        public virtual Kunde AlleKunde { get; set; }
    }
}
