
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KreditrechnerLAP.logic
{

using System;
    using System.Collections.Generic;
    
public partial class Kunde
{

    public int ID { get; set; }

    public string Vorname { get; set; }

    public string Nachname { get; set; }

    public System.DateTime Geburtsdatum { get; set; }

    public Nullable<int> FKTitel { get; set; }

    public Nullable<int> FKFamilienstand { get; set; }

    public string FKStaatsbuergerschaft { get; set; }

    public Nullable<int> FKWohnart { get; set; }

    public Nullable<int> FKAusbildung { get; set; }

    public string Idendifikationsnummer { get; set; }

    public Nullable<int> FKIdentifikationsArt { get; set; }

    public string Geschlecht { get; set; }

    public Nullable<int> FKArbeitgeber { get; set; }



    public virtual Ausbildung Ausbildung { get; set; }

    public virtual Familienstand Familienstand { get; set; }

    public virtual FinanzielleSituation FinanzielleSituation { get; set; }

    public virtual IdentifikationsArt IdentifikationsArt { get; set; }

    public virtual Kontaktdaten Kontaktdaten { get; set; }

    public virtual Konto Konto { get; set; }

    public virtual Kredit Kredit { get; set; }

    public virtual Land Staatsbuerger { get; set; }

    public virtual Titel Titel { get; set; }

    public virtual Wohnart Wohnart { get; set; }

    public virtual Arbeitgeber Arbeitgeber { get; set; }

}

}
