//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KreditrechnerLAP.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunde
    {
        public int ID { get; set; }
        public string Vorname { get; set; }
        public string Nachname { get; set; }
        public System.DateTime Geburtsdatum { get; set; }
        public Nullable<int> FKTitel { get; set; }
        public Nullable<int> FKFamilienstand { get; set; }
        public string FKStaatsbuergerschaft { get; set; }
        public Nullable<int> FKWohnart { get; set; }
        public Nullable<int> FKAusbildung { get; set; }
        public string Idendifikationsnummer { get; set; }
        public Nullable<int> FKIdentifikationsArt { get; set; }
        public string Geschlecht { get; set; }
    
        public virtual Arbeitgeber AlleArbeitgeber { get; set; }
        public virtual Ausbildung AlleAusbildung { get; set; }
        public virtual Familienstand AlleFamilienstand { get; set; }
        public virtual FinanzielleSituation AlleFinanzielleSituation { get; set; }
        public virtual IdentifikationsArt AlleIdentifikationsArt { get; set; }
        public virtual Kontaktdaten AlleKontaktdaten { get; set; }
        public virtual Konto AlleKonto { get; set; }
        public virtual Kredit AlleKredit { get; set; }
        public virtual Land AlleLand { get; set; }
        public virtual Titel AlleTitel { get; set; }
        public virtual Wohnart AlleWohnart { get; set; }
    }
}
