

//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KreditrechnerLAP.logic
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class dbKreditInstitutEntities : DbContext
{
    public dbKreditInstitutEntities()
        : base("name=dbKreditInstitutEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Arbeitgeber> AlleArbeitgeber { get; set; }

    public DbSet<Ausbildung> AlleAusbildungen { get; set; }

    public DbSet<Beschaeftigungsart> AlleBeschaeftigungsart { get; set; }

    public DbSet<Branche> AlleBranchen { get; set; }

    public DbSet<Einstellungen> tblEinstellungen { get; set; }

    public DbSet<Familienstand> AlleFamilienStandsAngaben { get; set; }

    public DbSet<FinanzielleSituation> AlleFinanzielleSituationen { get; set; }

    public DbSet<IdentifikationsArt> AlleIdentifikationsArten { get; set; }

    public DbSet<Kontaktdaten> AlleKontaktdaten { get; set; }

    public DbSet<Konto> AlleKonto { get; set; }

    public DbSet<Kredit> AlleKredite { get; set; }

    public DbSet<Kunde> AlleKunden { get; set; }

    public DbSet<Land> AlleLänder { get; set; }

    public DbSet<Ort> AlleOrt { get; set; }

    public DbSet<Titel> AlleTitel { get; set; }

    public DbSet<Wohnart> AlleWohnarten { get; set; }

}

}

