//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KreditrechnerLAP.logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbKreditInstitutEntities : DbContext
    {
        public dbKreditInstitutEntities()
            : base("name=dbKreditInstitutEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Arbeitgeber> AlleArbeitgeber { get; set; }
        public DbSet<Ausbildung> AlleAusbildung { get; set; }
        public DbSet<Beschaeftigungsart> AlleBeschaeftigungsart { get; set; }
        public DbSet<Branche> AlleBranchen { get; set; }
        public DbSet<Einstellungen> tblEinstellungen { get; set; }
        public DbSet<Familienstand> AlleFamilienstand { get; set; }
        public DbSet<FinanzielleSituation> AlleFinanzielleSituation { get; set; }
        public DbSet<IdentifikationsArt> AlleIdentifikationsArt { get; set; }
        public DbSet<Kontaktdaten> AlleKontaktdaten { get; set; }
        public DbSet<Konto> AlleKonto { get; set; }
        public DbSet<Kredit> AlleKredit { get; set; }
        public DbSet<Kunden> AlleKunde { get; set; }
        public DbSet<Land> AlleLand { get; set; }
        public DbSet<Ort> AlleOrt { get; set; }
        public DbSet<Titel> AlleTitel { get; set; }
        public DbSet<Wohnart> AlleWohnart { get; set; }
    }
}
