//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KreditrechnerLAP.logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ort
    {
        public Ort()
        {
            this.AlleKontaktdaten = new HashSet<Kontaktdaten>();
        }
    
        public int ID { get; set; }
        public string PLZ { get; set; }
        public string Bezeichnung { get; set; }
        public string FKLand { get; set; }
    
        public virtual ICollection<Kontaktdaten> AlleKontaktdaten { get; set; }
        public virtual Land AlleLand { get; set; }
    }
}
