
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KreditrechnerLAP.logic
{

using System;
    using System.Collections.Generic;
    
public partial class Ort
{

    public Ort()
    {

        this.AlleKontaktdaten = new HashSet<Kontaktdaten>();

    }


    public int ID { get; set; }

    public string PLZ { get; set; }

    public string Bezeichnung { get; set; }

    public string FKLand { get; set; }



    public virtual ICollection<Kontaktdaten> AlleKontaktdaten { get; set; }

    public virtual Land Land { get; set; }

}

}
